name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Check Docker version
      run: docker -v

    - name: Build Docker image
      run: docker build -t testexpress:latest .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag testexpress:latest ${{ secrets.DOCKER_USERNAME }}/myexpressapp:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myexpressapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH and Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: 20.240.194.164
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/myexpressapp:latest
            docker stop myexpressapp || true
            docker rm myexpressapp || true
            docker run -d --name myexpressapp -p 3939:3939 ${{ secrets.DOCKER_USERNAME }}/myexpressapp:latest
