name: CI/CD Pipeline for Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull fantik94/myexpressapp:latest
          docker stop myexpressapp || true
          docker rm myexpressapp || true
          docker run -d --name myexpressapp -p 3939:3939 fantik94/myexpressapp:latest